// <auto-generated />
namespace MvcTripLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201703062238537_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201703062238537_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201703062253350_201703062238537_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
